import Head from 'next/head'
import { useAuth } from '../shared/authContext'
import { ReactNode, useState } from 'react'
import SignInComponent from '../components/signin'
import MetaDataComponent from '../components/meta'
import TimetableComponent from '../components/timetable'
import { Transition } from '@headlessui/react'

/**
 * Single Page Application!
 */
interface SPAProps {
  children: ReactNode
  title: string
}

function MultiComponent(props: SPAProps): JSX.Element {
  const [prevState, setPrevState] = useState(props)
  return (
    <Transition
      show={props.title == prevState.title}
      enter="transition duration-700 delay-150"
      enterFrom="opacity-0"
      enterTo="opactity-100"
      leave="transition duration-500"
      leaveFrom="opacity-100"
      leaveTo="opacity-0"
      className="flex flex-col mb-8 shadow-lg text-center items-center"
      afterLeave={() => setPrevState(props)}
    >
      {prevState.title !== null && (
        <h2 className="text-black text-xl font-medium py-4 rounded-t-lg bg-gradient-to-br from-paris-daisy-400 to-paris-daisy-600 p-4 w-full">
          {prevState.title}
        </h2>
      )}
      <div
        className={
          'text-black md:px-4 py-4 bg-white dark:bg-gray-800 dark:text-gray-200 ' +
          (prevState.title !== null ? 'rounded-b-lg' : 'rounded-lg filter drop-shadow-md')
        }
      >
        {prevState.children}
      </div>
    </Transition>
  )
}

export default function MainPage(): JSX.Element {
  const auth = useAuth()
  function renderPage(): JSX.Element {
    let children: JSX.Element = null,
      title: string = null
    if (!auth.user) {
      children = <SignInComponent />
      title = 'เข้าสู่ระบบ'
    }
    if (auth.user && !auth.metadata) {
      title = 'อีกแค่นิดเดียว'
      children = <MetaDataComponent />
    }
    if (children === null) {
      // No page matched, load Main Time component
      children = <TimetableComponent />
    }
    return <MultiComponent title={title}>{children}</MultiComponent>
  }
  return (
    <div className="circle min-h-screen flex flex-col items-center justify-center dark:bg-gray-900 dark:text-white">
      <Head>
        <title>PM-Rianarai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col w-full items-center justify-center">
        <header className="py-8 sm:py-10 w-full flex flex-col items-center">
          <h1 className="text-4xl font-bold creative-font">เรียนอะไร?</h1>
          <p className="p-4 font-light">คุณไม่รู้ เราก็ไม่รู้เหมือนกัน</p>
        </header>
        {renderPage()}
      </main>

      <footer className="bg-white dark:bg-gray-800 dark:text-white flex justify-center items-center w-full p-8 border-t">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="text-sm underline"
        >
          เกี่ยวกับเว็บไซต์นี้
        </a>
      </footer>
    </div>
  )
}
